camel:
  springboot:
    # The Camel context name
    name: CamelRestSql
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /camel-rest-sql/*
    quartz2:
      properties:
        org.quartz.scheduler.skipUpdateCheck: "true"
        org.quartz.scheduler.instanceName: ClusteredScheduler
        org.quartz.scheduler.instanceId: AUTO
        org.quartz.scheduler.jobFactory.class: org.quartz.simpl.SimpleJobFactory
        org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
        org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        org.quartz.jobStore.useProperties: "false"
        org.quartz.jobStore.dataSource: myDS
        org.quartz.jobStore.tablePrefix: QRTZ_
        org.quartz.jobStore.isClustered: "true"
        org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
        org.quartz.threadPool.threadCount: "10"
        org.quartz.jobStore.clusterCheckinInterval: "20000"

        org.quartz.dataSource.myDS.driver: com.mysql.jdbc.Driver
        org.quartz.dataSource.myDS.URL: jdbc:mysql://localhost:3306/sampledb?useSSL=false
        org.quartz.dataSource.myDS.user: root
        org.quartz.dataSource.myDS.password: my-secret-pw
        org.quartz.dataSource.myDS.maxConnections: "12"

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
