# get mysql connection information from environment variables
mysql:
  quartz:
    service:
      # The name of the service hosting the MySQL database server,
      # can be customized using the 'MYSQL_SERVICE_NAME' env variable to use a different service
      # name:     mysql
      name: ${MYSQL_QUARTZ_SERVICE_NAME}
      # The database to use, can be customized using the 'MYSQL_SERVICE_DATABASE' env variable
      database: ${MYSQL_QUARTZ_SERVICE_DATABASE}
      username: ${MYSQL_QUARTZ_SERVICE_USERNAME}
      password: ${MYSQL_QUARTZ_SERVICE_PASSWORD}

camel:
  springboot:
    # The Camel context name
    name: CamelRestSql
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /camel-rest-sql/*
    quartz2:
      properties:
        org.quartz.scheduler.skipUpdateCheck: "true"
        org.quartz.scheduler.instanceName: ClusteredScheduler
        org.quartz.scheduler.instanceId: AUTO
        org.quartz.scheduler.jobFactory.class: org.quartz.simpl.SimpleJobFactory
        org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
        org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        org.quartz.jobStore.useProperties: "false"
        org.quartz.jobStore.dataSource: myDS
        org.quartz.jobStore.tablePrefix: QRTZ_
        org.quartz.jobStore.isClustered: "true"
        org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
        org.quartz.threadPool.threadCount: "10"
        org.quartz.jobStore.clusterCheckinInterval: "20000"

        org.quartz.dataSource.myDS.driver: com.mysql.jdbc.Driver
        org.quartz.dataSource.myDS.URL: jdbc:mysql://${mysql.quartz.service.name}:3306/${mysql.quartz.service.database}
        org.quartz.dataSource.myDS.user: ${mysql.quartz.service.username}
        org.quartz.dataSource.myDS.password: ${mysql.quartz.service.password}
        org.quartz.dataSource.myDS.maxConnections: "12"

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
